services:
  database:
    image: "postgres:16.0-alpine3.18" 
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "my_password"
    ports:
      - "5433:5433"
    deploy:
      resources:
        limits:
          memory: 2096M
        reservations:
          memory: 2048M